use_frameworks!
source 'git@192.168.3.56:ios/PodSpec/TopbandSpec.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
target 'testFramwork' do
	pod 'TBUser_Http_Lib/TBUser_Http'
	pod 'TBUser_Http_Lib/TBUser_Http_Ex'
	pod 'TBUser_Http_Lib/TBUser_Http_Ex/TBCloud'
end

